### ISSUE TITLE
Issue with rdk init command

### ISSUE THREAD

**Issue by jsposato** [michaelborchert/rdk#2]
Getting this when running `rdk init`

```
Running init!
Found Config Recorder: default
Found Config Role: arn:aws:iam::xxxxxxxxxx:role/config-role
Found Bucket: config-bucket-xxxxxxxxxxxxx
Config Service is ON
Config setup complete.
Creating Code bucket config-rule-code-bucket-xxxxxxxxxxxxxus-east-1
Traceback (most recent call last):
  File "/usr/local/bin/rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 50, in process_command
    exit_code = method_to_call()
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 178, in init
    'LocationConstraint': my_session.region_name
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
```

Not sure what else you may need to debug

**Comment by michaelborchert** [comment]
Do you have your default region set, either for the profile you're using in the ~/.aws/config file or by setting the AWS_DEFAULT_REGION environment variable?

**Comment by michaelborchert** [comment]
Nevermind, figured out that it was an issue with the different S3 API requirements for us-east-1 vs. other regions.  I replicated the issue, and have pushed a fix to github and pypi.  Let me know if your issue is resolved, thanks!

**Comment by jsposato** [comment]
Cool, I'll update and test today.

**Comment by jsposato** [comment]
Able to init in us-east-1, thanks!
